version: '3.0'

services:
  mysqldb:
    image: mysql
    restart: unless-stopped
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=1234567890
      - MYSQL_DATABASE=docker_demo
    volumes:
      - db:/var/lib/mysql

  springapp:
    depends_on:
      - mysqldb
    image: prabuddha66/docker-demo
    restart: on-failure
    ports: 
      - 8080:8080
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url":"jdbc:mysql://mysqldb:3306/docker_demo",
        "spring.datasource.username":"root",
        "spring.datasource.password":"1234567890",
        "spring.jpa.show-sql":"true",
        "spring.jpa.hibernate.ddl-auto":"update",
        "spring.jpa.properties.hibernate.dialect":"org.hibernate.dialect.MySQL5Dialect"
       }'
volumes:
  db: